trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: GitHubPATGroup
- name: buildConfiguration
  value: 'Release'

steps:
- task: DotNetCoreInstaller@0
  displayName: Install Latest .NET Core 3.0 SDK
  inputs:
    packageType: 'sdk'
    version: '3.0.100-preview6-012264'

- task: DotNetCoreCLI@2
  displayName: Publish App
  inputs:
    command: publish
    # Important: If you zip the publish, the GitHub Pages script will need to unzip it first
    zipAfterPublish: false
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)/s/BlazorShoppingList/dist
    artifactName: 'Dist'

- script: |
    git config --global user.name "$NAME"
    git config --global user.email "$EMAIL"
    git clone https://$PAT@github.com/$NAME/blazor-shopping.git $(Build.ArtifactStagingDirectory)/git
    cd $(Build.ArtifactStagingDirectory)/git
    git checkout -b master
    cp -R $(Build.ArtifactStagingDirectory)/s/BlazorShoppingList/dist/* $(Build.ArtifactStagingDirectory)/git
    git add -A
    git commit -m "Create build $(Build.BuildId)"
    git push https://$PAT@github.com/$NAME/blazor-shopping.git master
  displayName: 'Publish to GitHub Pages'
  env:
    PAT: $(GitHubPAT)
    NAME: $(GitHubName)
    EMAIL: $(GitHubEmail)